name: Developer_Branch_CI
on: [workflow_call]
jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Unit Test Case
        run: echo Unit Test

      - name: Unit Integration Case
        run: echo Integration test

      - name: SAST Scans
        run: echo SAST Scans





