name: Developer_Branch_CI
on: [workflow_call]
jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Unit Test Case
        run: echo npm test

      - name: Integration Test
        run: echo Integration test

      - name: Code Quality
        shell: bash
        run: sonar-scanner -Dsonar.host.url=http://172.31.23.70:9000 -Dsonar.login="${SONAR_USER}" -Dsonar.password="${SONAR_PASS}" -Dsonar.projectkey=expense-backend -X
        env:
          SONAR_USER: ${{ secrets.SONAR_USER }}
          SONAR_PASS: ${{ secrets.SONAR_PASS }}







