name: Developer_Branch_CI
on: [workflow_call]

jobs:
  CI_Steps:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unit Tests
        run: echo npm test

      - name: Integration Tests
        run: echo Integration Tests

      - name: Code Quality & Quality Gate
        shell: bash
        run: sonar-scanner -Dsonar.host.url=http://172.31.23.70:9000 -Dsonar.login="${SONAR_USER}" -Dsonar.password="${SONAR_PASS}" -Dsonar.projectKey=${service_name} -Dsonar.qualitygate.wait=true
        env:
          SONAR_USER: ${{ secrets.SONAR_USER }}
          SONAR_PASS: ${{ secrets.SONAR_PASS }}
          service_name: ${{ inputs.service_name }}







