name: Tags_CI
on: [workflow_call]
jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: SAST Scans
        run: echo SAST Scans

      - name: SCA Scans
        run: echo SCA Scans

      - name: Detect Secrets in Source Code
        run: echo Detect Secrets

      - name: Produce Artifacts
        run: echo Produce artifacts
